### ISSUE TITLE
KHI: Add related documents in the mappings and UI

### ISSUE THREAD

**Issue by MinadakisNikos** [ArtResearch/pharos-mappings#203] opened 2021-07-09 10:11 UTC
"Related documents" should be displayed. 

Important for copies of works of art, for example: https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fpharos%2Fartwork%2Fc29a6b8572ecfa8ad371c6f12fe5a4aa859417ed
KHI-Page:

http://photothek.khi.fi.it/documents/obj/70003602?medium=70003602%2Ffld0005301x_p#1

🡪 Related documents are aob26 (kind of relation) and a2606 (document no.)

**Comment by mafragias** [comment] 2021-08-10 07:01
duplicate of https://github.com/ArtResearch/pharos-mappings/issues/197

**Closed by mafragias** 2021-08-10 07:01 UTC
Labels: enhancement, KHI
