### ISSUE TITLE
Harvard Fine Arts Library records

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#149] opened 2021-03-20 16:00 UTC
Can you check how many photograph records have been exported with repository "Harvard Fine Arts Library"? These should not be included in Pharos, although in many cases I Tatti and the Fine Arts Library have linked their photograph records with the same artwork record.

example: https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fphoto%2F1998.121

**Comment by mafragias** [comment] 2021-04-06 12:58
closed as duplicate of https://github.com/ArtResearch/pharos-mappings/issues/157

**Closed by mafragias** 2021-04-06 12:58 UTC
